# Generated by Django 3.1.7 on 2021-03-09 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='votes_to_skips',
            new_name='votes_to_skip',
        ),
    ]
